### ISSUE TITLE
Holding 'p' key pressed leads to an uncontrollable state

### ISSUE THREAD

**Issue by elpinal** [itchyny/bed#10] opened 2018-04-17 09:19 UTC
First, copying something by `y` command in visual mode.

Second, holding `p` key pressed to paste the copied text repeatedly.

Then, the `bed` program hangs up before long.

**Comment by itchyny** [comment] 2018-04-17 09:28
Yeah, this is what I found last night but could not find where it stucks.

**Comment by itchyny** [comment] 2018-04-21 15:29
This should be much better with 291f0dad15a7fc79ab920fab64862dc6f6381af1, but there still seem to be some deadlock somewhere :(

**Comment by itchyny** [comment] 2018-05-05 09:28
The problem is somehow resolved for now so I close the issue (c9bb5070b6b74e10ea0d497b1c405dd9325079c4 is probably related).

**Closed by itchyny** 2018-05-05 09:28 UTC
